--DROP TABLE users;
--DROP TABLE users_friend;
--DROP TABLE users_rate;
--DROP TABLE films;
--DROP TABLE films_genre;
--DROP TABLE film_category;
--DROP TABLE genre;
--DROP TABLE category;



/*ФИЛЬМЫ*/
CREATE TABLE IF NOT EXISTS films(
    film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_film varchar(40) NOT NULL,
    description varchar(200) NOT NULL,
    releaseDate date NOT NULL,
    duration integer NOT NULL,
    rate integer NOT NULL
);

/*ЖАНРЫ*/
CREATE TABLE IF NOT EXISTS genre(
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre varchar(40) NOT NULL
    );

/*ЖАНРЫ_СВЯЗЫВАЮЩАЯ*/
CREATE TABLE IF NOT EXISTS films_genre(
    film_id integer NOT NULL,
    genre_id integer NOT NULL
    );

/*КАТЕГОРИИ*/
CREATE TABLE IF NOT EXISTS category(
    category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category varchar(40) NOT NULL
    );

/*КАТЕГОРИИ_СВЯЗЫВАЮЩАЯ*/
CREATE TABLE IF NOT EXISTS film_category(
    film_id INTEGER NOT NULL,
    category_id integer NOT NULL
    );



/*ПОЛЬЗОВАТЕЛИ*/
CREATE TABLE IF NOT EXISTS users(
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_user varchar(40) NOT NULL,
    email varchar(20) NOT NULL,
    login varchar(20) NOT NULL,
    birthday date
    );

/*ДРЗЬЯ*/
CREATE TABLE IF NOT EXISTS users_friend(
    user_id integer NOT NULL,
    friend_id integer,
    status varchar(40) ,
    request_id integer
    );

/*ДРЗЬЯ-ФИЛЬМЫ_СВЯЗЫВАЮЩАЯ*/
CREATE TABLE IF NOT EXISTS users_rate(
    film_id integer NOT NULL,
    user_id integer NOT NULL
    );


INSERT INTO genre (genre) VALUES ( 'Комедия' );
INSERT INTO genre (genre) VALUES ( 'Драма' );
INSERT INTO genre (genre) VALUES ( 'Мультфильм' );
INSERT INTO genre (genre) VALUES ( 'Триллер' );
INSERT INTO genre (genre) VALUES ( 'Документальный' );
INSERT INTO genre (genre) VALUES ( 'Боевик' );

INSERT INTO category (category) VALUES ('G');
INSERT INTO category (category) VALUES ('PG');
INSERT INTO category (category) VALUES ('PG-13');
INSERT INTO category (category) VALUES ('R' );
INSERT INTO category (category) VALUES ('NC-17');




